gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
# source: 
destination: _site

assets:
  cachebust: soft

# Site settings
title: Jerome Toole | Design & Development
description: Design and Development

intro: I'm a freelance designer and developer based in London. I love working on projects with a social aim and with organisations in the arts & culture sectors.

# Name of project on Github
# baseurl: 

permalink: :title

# Build settings
markdown: kramdown

sass:
    style: compressed