gems:
  - bourbon
  - neat
  - octopress-autoprefixer

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft

# Site settings
title: Jerome Toole | Design & Development
description: Design and Development

# Name of project on Github
baseurl: /build

permalink: :title

# Build settings
markdown: kramdown
